DELIMITER $$
CREATE PROCEDURE SP_FATORIAL(IN NUM INT)
BEGIN
	DECLARE COUNT INT DEFAULT 1;
    DECLARE RESULTADO INT DEFAULT 1;
    WHILE COUNT <= NUM DO
		SET RESULTADO = RESULTADO * COUNT;
		SET COUNT = COUNT + 1;
	END WHILE;
    SELECT RESULTADO;
END $$
CALL SP_FATORIAL(4);