-- DDL

-- DROP DATABASE AULA10;
CREATE DATABASE AULA10;
USE AULA10;

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL,
    URL_IMAGEM VARCHAR(255)
);

CREATE TABLE CLIENTES(
	ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(11),
    NR_CELULAR VARCHAR(15),
    EMAIL VARCHAR(150)
);

CREATE TABLE PRODUTOS(
	ID_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CATEGORIA INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    IMAGEM VARCHAR(255),
    VALOR DECIMAL,
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE CONTA(
	ID_CONTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    DATA_HORA_PAGAMENTO DATETIME,
    VALOR_TOTAL DECIMAL,
    CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE PEDIDOS(
	ID_PEDIDO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    ID_CONTA INT NOT NULL,
    QUANTIDADE INT,
    PRECO_TOTAL DECIMAL,
    CONSTRAINT FK_PEDIDOS_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
    CONSTRAINT FK_PEDIDO_CONTA FOREIGN KEY (ID_CONTA) REFERENCES CONTA(ID_CONTA)
);

-- INSERT
INSERT INTO CATEGORIA(NOME, URL_IMAGEM)
VALUES
('Pratos', NULL),
('Lanches', NULL),
('Sobremesas', NULL),
('Bebidas', NULL);

-- UPDATE
UPDATE CATEGORIA
SET NOME = 'Lanches saudáveis'
WHERE
	ID_CATEGORIA = 2;
    
-- DELETE
DELETE FROM CATEGORIA WHERE ID_CATEGORIA = 4;

-- SELECT
SELECT * FROM CATEGORIA;
